server:
  port: 8300

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://aleibaba.top:3306/selectCourse?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhanglei
  redis:
    #数据库索引
    database: 1
    host: 8.140.184.29
    port: 6379
    password: zhang
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000
  application:
    name: nacos-student
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.184.29:8848 #配置linux
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        # 默认 8719端口，假如被占用从8719开始+1扫描直到直到未被占用的端口
        port: 8719
        #客户端地址，，注意：sentinel在服务器客户端也要服务器，要公网ip才能监控到
#        ipclient: 192.168.43.240
      datasource:
        ds1:
          nacos:
            server-addr: 8.140.184.29:8848 #nacos地址
            dataId: nacos-student  #微服务名称
            groupId: DEFAULT_GROUP  #默认分组
            data-type: json #数据格式
            rule-type: flow #流控规则
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  #配置mybatis扫描mapper文件xml的路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level.com.student.mapper: DEBUG


feign:
  sentinel:
    enabled: true

