

#    gateway:
#      discovery:
#        locator:
#          enabled: true # 开启从服务在注册中心动态创建路由的功能
#      routes: # 可以配置多个路由
#        - id: payment_routh # 路由id，没有固定规则但要求唯一
#          #          uri:  http://localhost:8001 # 匹配后提供服务的路由地址
#          uri:  lb://cloud-payment-service
#          predicates:
#            - Path=/student/** # 路径相匹配的进行路由
#            - After=2020-05-26T17:07:03.043+08:00[Asia/Shanghai]
        #            - Cookie=username,wxh
#
#        - id: payment_routh2 # 路由id，没有
#          #          uri:  http://localhost:8001 # 匹配后提供服务的路由地址
#          uri:  lb://cloud-payment-service
#          predicates:
#            - Path=/payment/create # 路径相匹配的进行路由